#!/usr/bin/env node
// Bundles each src/styles/<id>.ts into a self-contained dist/styles/<id>.mjs.
// The output must stay self-contained: the picker copies exactly ONE of these
// into the user's stable directory, where the repo's relative paths no longer
// exist.
import { build } from 'esbuild';
import { readdir, mkdir, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(root, 'src', 'styles');
const outDir = path.join(root, 'dist', 'styles');

const entries = (await readdir(srcDir))
  .filter((f) => f.endsWith('.ts'))
  .map((f) => path.join(srcDir, f));

if (entries.length === 0) {
  console.error('No styles found in src/styles');
  process.exit(1);
}

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

await build({
  entryPoints: entries,
  outdir: outDir,
  outExtension: { '.js': '.mjs' },
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node18',
  minify: false,
  legalComments: 'none',
  banner: {
    js: '// Generated by `npm run build` — do not edit by hand.\n// Source: src/styles/ — https://github.com/Priotts/cc-status-line-picker',
  },
});

// config.default.json is the template the installer seeds into the user's
// install directory. Generating it from DEFAULT_CONFIG keeps the shipped
// defaults and the code that consumes them from drifting apart.
const configBundle = path.join(root, 'dist', '.config-defaults.mjs');
await build({
  entryPoints: [path.join(root, 'src', 'lib', 'config.ts')],
  outfile: configBundle,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node18',
  legalComments: 'none',
});

const { DEFAULT_CONFIG } = await import(pathToFileURL(configBundle).href);
await writeFile(
  path.join(root, 'config.default.json'),
  `${JSON.stringify(
    {
      $comment:
        'Template copied to ~/.claude/statusline-picker/config.json on first install. Edit that copy, not this file. Every key is optional; anything omitted or invalid falls back to these defaults. Colors accept a name ("cyan"), a 256-color index ("123"), or a raw SGR sequence ("38;5;123").',
      ...DEFAULT_CONFIG,
    },
    null,
    2,
  )}\n`,
);
await rm(configBundle, { force: true });

console.log(`Build ok: ${entries.length} styles in dist/styles/, config.default.json regenerated`);
